# Week 1 Assignment

### Step 1 

In [6]:
import numpy as np

### Step 2 

#### Array of Integers

In [12]:
arr = np.array([[1,2,3],[7,8,9]])
print("Array = ")
print(arr)
print()
print("Dimensions = ")
print(arr.ndim)

Array = 
[[1 2 3]
 [7 8 9]]

Dimensions = 
2


#### Array of Floats

In [17]:
arr = np.array([[1.2,2.23,3.213],[7.11,8.11,9.11]])
print("Array = ")
print(arr)
print()
print("Dimensions = ")
print(arr.ndim)

Array = 
[[1.2   2.23  3.213]
 [7.11  8.11  9.11 ]]

Dimensions = 
2


#### Array of Complex Numbers

In [18]:
arr = np.array([1.2 + 0.3j,2.23] , dtype=complex)
print("Array = ")
print(arr)
print()
print("Dimensions = ")
print(arr.ndim)

Array = 
[1.2 +0.3j 2.23+0.j ]

Dimensions = 
1


### Step 3

#### Addition of 2 matrices

In [30]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([[7,8,9],[10,11,12]])
print(np.add(arr_1,arr_2))

[[ 8 10 12]
 [14 16 18]]


#### Transpose 

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print("Before Transpose = ")
print(arr)
print("After Transpose = ")
print(arr.transpose())

Before Transpose = 
[[1 2 3]
 [4 5 6]]
After Transpose = 
[[1 4]
 [2 5]
 [3 6]]


#### Multiplication: Dot Product

In [28]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])
print(np.dot(arr_1,arr_2))

[[19 22]
 [43 50]]


#### Multiplication: Element Wise 

In [29]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])
print(np.multiply(arr_1,arr_2))

[[ 5 12]
 [21 32]]


#### Accesing matrix elements 

In [32]:
arr = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])
print("arr[0][1] =", arr[0][1])  
print("arr[2][2] =", arr[2][2])
print("arr[-1][-1] =", arr[-1][-1])

arr[0][1] = 4
arr[2][2] = 11
arr[-1][-1] = 19


### Step 4

#### Python Slicing and Reversing

In [43]:
nums = [10, 20, 30, 40, 50, 60, 70, 80, 90]
print(nums[2:7])
print(nums[-3:-1])
print("Reversing the list")
print(nums[::-1])

[30, 40, 50, 60, 70]
[70, 80]
Reversing the list
[90, 80, 70, 60, 50, 40, 30, 20, 10]


### Step 5

#### Numpy with Datasets 

In [61]:
import pandas as pd
data = pd.read_csv("diabetes.csv")
print("Column Extraction = ")
array_1 = np.array(data['Age'])
print(array_1)
print()
array_2 = np.array(data[0:2])
print("Row Extraction = ")
print(array_2)


Column Extraction = 
[40 58 41 45 60 55 57 66 67 70 44 38 35 61 60 58 54 67 66 43 62 54 39 48
 58 32 42 52 38 53 57 41 37 54 49 48 60 63 35 30 53 50 50 35 40 48 60 60
 35 46 36 50 60 50 51 38 66 53 59 39 65 35 55 60 45 40 30 35 25 50 40 35
 65 38 50 55 48 55 39 43 35 47 50 48 35 49 38 28 68 35 45 48 40 40 36 56
 30 31 35 39 48 85 90 72 70 69 58 47 25 39 53 52 68 79 55 45 30 45 65 34
 48 35 40 47 38 55 66 57 32 48 47 43 30 16 35 66 54 58 51 40 47 62 49 53
 68 61 39 38 44 45 50 42 55 57 62 33 55 48 56 38 28 68 35 45 48 40 57 41
 37 54 49 48 60 63 35 30 53 50 50 35 40 31 35 39 48 85 90 72 70 69 58 54
 64 36 43 31 66 61 58 69 40 28 37 34 30 67 60 58 54 43 39 40 43 49 47 45
 57 72 30 27 38 43 40 55 68 29 37 30 45 47 35 32 56 50 52 26 60 65 72 30
 45 65 70 35 54 30 46 53 42 55 48 55 39 43 35 47 50 48 35 62 33 55 48 56
 38 28 68 35 45 48 40 57 47 45 57 72 30 27 38 43 40 47 45 57 72 30 27 38
 43 40 54 30 46 53 42 55 48 55 39 43 35 47 61 58 69 40 28 37 34 30 67 60
 58 54 43 33 55 36 28 34 65 34