# Week 1 Assignment

### Step 1 

In [6]:
import numpy as np

### Step 2 

#### Array of Integers

In [12]:
arr = np.array([[1,2,3],[7,8,9]])
print("Array = ")
print(arr)
print()
print("Dimensions = ")
print(arr.ndim)

Array = 
[[1 2 3]
 [7 8 9]]

Dimensions = 
2


#### Array of Floats

In [17]:
arr = np.array([[1.2,2.23,3.213],[7.11,8.11,9.11]])
print("Array = ")
print(arr)
print()
print("Dimensions = ")
print(arr.ndim)

Array = 
[[1.2   2.23  3.213]
 [7.11  8.11  9.11 ]]

Dimensions = 
2


#### Array of Complex Numbers

In [18]:
arr = np.array([1.2 + 0.3j,2.23] , dtype=complex)
print("Array = ")
print(arr)
print()
print("Dimensions = ")
print(arr.ndim)

Array = 
[1.2 +0.3j 2.23+0.j ]

Dimensions = 
1


### Step 3

#### Addition of 2 matrices

In [30]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([[7,8,9],[10,11,12]])
print(np.add(arr_1,arr_2))

[[ 8 10 12]
 [14 16 18]]


#### Transpose 

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print("Before Transpose = ")
print(arr)
print("After Transpose = ")
print(arr.transpose())

Before Transpose = 
[[1 2 3]
 [4 5 6]]
After Transpose = 
[[1 4]
 [2 5]
 [3 6]]


#### Multiplication: Dot Product

In [28]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])
print(np.dot(arr_1,arr_2))

[[19 22]
 [43 50]]


#### Multiplication: Element Wise 

In [29]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])
print(np.multiply(arr_1,arr_2))

[[ 5 12]
 [21 32]]


#### Accesing matrix elements 

In [32]:
arr = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])
print("arr[0][1] =", arr[0][1])  
print("arr[2][2] =", arr[2][2])
print("arr[-1][-1] =", arr[-1][-1])

arr[0][1] = 4
arr[2][2] = 11
arr[-1][-1] = 19


### Step 4

#### Python Slicing and Reversing

In [43]:
nums = [10, 20, 30, 40, 50, 60, 70, 80, 90]
print(nums[2:7])
print(nums[-3:-1])
print("Reversing the list")
print(nums[::-1])

[30, 40, 50, 60, 70]
[70, 80]
Reversing the list
[90, 80, 70, 60, 50, 40, 30, 20, 10]


### Step 5

#### Numpy with Datasets 

In [53]:
import pandas as pd
data = pd.read_csv("diabetes.csv")
array = np.array(data['Age'])
print(array)


Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [60]:
print(data[0:2])
array = np.array(data[0:2])
print("Array")

print()
print()
print()

print(array)

   Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
Array



[[40 'Male' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
  'Yes' 'Yes' 'Yes' 'Positive']
 [58 'Male' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes'
  'No' 'Yes' 'No' 'Positive']]
